/**
 * Sensei SaaS template contract — 137 templates across 11 categories.
 */
export const SENSEI_TEMPLATE_CONTRACT = {
  'auth-security': [
    'email-verification',
    'magic-link-login',
    'otp-2fa-code',
    'password-reset-request',
    'password-reset-success',
    'password-changed',
    'new-device-login',
    'suspicious-activity-alert',
    '2fa-enabled',
    '2fa-disabled',
    'recovery-codes-generated',
    'account-locked',
    'email-change-request',
    'email-changed-confirmation',
    'passkey-added',
    'passkey-removed',
    'sso-configured',
    'session-expired',
  ],
  'account-lifecycle': [
    'welcome-post-signup',
    'welcome-email-confirmed',
    'profile-completion-reminder',
    'account-deletion-requested',
    'account-deletion-scheduled',
    'account-deletion-cancelled',
    'account-permanently-deleted',
    'data-export-ready',
    'data-export-failed',
    'account-suspended',
    'account-reactivated',
    'goodbye-churn',
  ],
  onboarding: [
    'setup-checklist-progress',
    'first-action-celebration',
    'feature-spotlight',
    'inactive-day-3',
    'inactive-day-7',
    'inactive-day-14',
    'onboarding-complete',
    'we-miss-you',
  ],
  billing: [
    'trial-started',
    'trial-ending-7-days',
    'trial-ending-3-days',
    'trial-ending-tomorrow',
    'trial-ended',
    'trial-extended',
    'trial-converted-paid',
    'subscription-started',
    'subscription-renewed',
    'upcoming-renewal-notice',
    'subscription-upgraded',
    'subscription-downgraded',
    'subscription-paused',
    'subscription-resumed',
    'subscription-cancelled',
    'subscription-cancelled-involuntary',
    'receipt-invoice-paid',
    'payment-failed-attempt-1',
    'payment-failed-attempt-2',
    'payment-failed-final',
    'payment-method-expiring',
    'payment-method-updated',
    'payment-method-removed',
    'refund-issued',
    'chargeback-notice',
    'plan-limit-warning-80',
    'plan-limit-reached-100',
    'overage-charges',
  ],
  'usage-api': [
    'usage-cap-warning',
    'usage-cap-hit',
    'quota-reset',
    'api-key-created',
    'api-key-rotated',
    'api-key-revoked',
    'rate-limit-hit',
    'webhook-delivery-failure',
    'webhook-restored',
  ],
  notifications: [
    'mention-tag',
    'comment-reply',
    'direct-message',
    'task-assigned',
    'task-due-soon',
    'task-overdue',
    'approval-requested',
    'approval-granted-rejected',
    'document-shared',
    'file-uploaded-processed',
    'project-status-change',
    'daily-digest',
    'weekly-digest',
    'custom-reminder',
    'realtime-alert',
  ],
  team: [
    'team-invitation',
    'invitation-accepted-admin',
    'invitation-declined',
    'invitation-reminder',
    'invitation-expired',
    'member-joined',
    'member-left',
    'member-removed',
    'role-changed',
    'workspace-ownership-transferred',
    'workspace-deleted',
    'guest-access-granted',
  ],
  integrations: [
    'integration-connected',
    'integration-disconnected',
    'integration-failed',
    'oauth-app-authorized',
    'oauth-app-revoked',
    'sync-completed',
    'sync-failed',
  ],
  'product-platform': [
    'changelog-digest',
    'feature-announcement',
    'beta-access-invitation',
    'maintenance-scheduled',
    'maintenance-starting',
    'maintenance-completed',
    'incident-notification',
    'incident-resolved',
    'post-incident-report',
    'security-advisory',
    'terms-privacy-update',
    'service-deprecation',
  ],
  'support-feedback': [
    'support-ticket-created',
    'support-ticket-replied',
    'support-ticket-resolved',
    'nps-survey',
    'csat-survey',
    'feature-request-acknowledged',
    'bug-report-acknowledged',
    'review-request',
  ],
  commerce: [
    'license-key-delivered',
    'subscription-gift-sent',
    'subscription-gift-received',
    'referral-signed-up',
    'referral-converted',
    'affiliate-payout',
    'credits-added',
    'credits-expiring',
  ],
} as const;

export type SenseiTemplateCategory = keyof typeof SENSEI_TEMPLATE_CONTRACT;

export function getSenseiContractEntries(): Array<{ category: string; name: string }> {
  return Object.entries(SENSEI_TEMPLATE_CONTRACT).flatMap(([category, names]) =>
    names.map((name) => ({ category, name })),
  );
}

const total = getSenseiContractEntries().length;
if (total !== 137) {
  throw new Error(`SENSEI_TEMPLATE_CONTRACT must define exactly 137 templates, got ${total}`);
}
